"use strict";


const ActionTypes = {
  ENTER_PIE_CHART_NAME: 'ENTER_PIE_CHART_NAME',
  ADD_PIE_SLICE: 'ADD_PIE_SLICE',
  CHANGE_SLICE_NAME: 'CHANGE_SLICE_NAME',
  CHANGE_NAME: 'CHANGE_NAME',
  CELL_CHANGED: 'CELL_CHANGED'
};

export default ActionTypes;
